### ISSUE TITLE
fontforge fails to launch

### ISSUE THREAD

**Issue by matthiasclasen** [flathub/org.fontforge.FontForge#1] opened 2019-04-08 21:06 UTC
I installed fontforge from flathub, but have no luck trying to launch it.

Here is what I get, trying to launch it manually:

```
[mclasen@ibm-p8-kvm-03-guest-02 ~]$ flatpak run --command=sh org.fontforge.FontForge 
[📦 org.fontforge.FontForge ~]$ fontforge 
Copyright (c) 2000-2018 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 08:38 UTC 22-Mar-2019-ML-D.
 Based on source from git with hash: 
Floating point exception (core dumped)
```

**Comment by muelli** [comment] 2019-04-09 06:52
hm. you haven't installed from https://flathub.org/apps/details/org.fontforge.FontForge, right? Because it doesn't even show up there.  Have you used the command line to install the app?

**Comment by muelli** [comment] 2019-04-09 08:51
I can't reproduce this.

```
➜ ~>flatpak run --command=sh org.fontforge.FontForge
[📦 org.fontforge.FontForge ~]$ fontforge
Copyright (c) 2000-2018 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 08:38 UTC 22-Mar-2019-ML-D.
 Based on source from git with hash: 

```

and the "open font" window appears. I've tried with an empty `~/.var/app/org.fontforge.FontForge` folder, too. hm.

Do you have a strange setup? Like non-x86?
Can you get a stacktrace and file a bug upstream?

**Comment by matthiasclasen** [comment] 2019-04-09 12:41
its an x86-64 silverblue vm. I'll try to get some more info

**Comment by muelli** [comment] 2019-10-24 11:08
let me close this for now. Please reopen if it still doesn't work.

**Closed as completed by muelli** 2019-10-24 11:08 UTC
